### ISSUE TITLE
半角カナ

### ISSUE THREAD

**Issue by management-partners** [k1LoW/jquery-autokana#1]
半角カナに交換できますか

**Comment by k1LoW** [comment]
いいえ。残念ながら半角カナには対応していません。また、対応予定はありません 🙏

**Comment by management-partners** [comment]
いいえ。下記にソースを追加すると、対応できると思います

function convertSmallKana(kanaVal) {
            console.log('kanaVal');
            console.log(kanaVal);
            var smallKana = Array('ｶ', 'ｷ', 'ｸ', 'ｹ', 'ｺ', 'ｻ', 'ｼ', 'ｽ', 'ｾ', 'ｿ', 'ﾀ', 'ﾁ', 'ﾂ', 'ﾃ', 'ﾄ', 'ﾅ', 'ﾆ', 'ﾇ', 'ﾈ', 'ﾉ', 'ﾊ', 'ﾋ', 'ﾌ', 'ﾍ', 'ﾎ', 'ﾏ', 'ﾐ', 'ﾑ', 'ﾒ', 'ﾓ', 'ﾗ', 'ﾘ', 'ﾙ', 'ﾚ', 'ﾛ', 'ﾜ', 'ｦ', 'ﾝ', 'ｶﾞ', 'ｷﾞ', 'ｸﾞ', 'ｹﾞ', 'ｺﾞ', 'ｻﾞ', 'ｼﾞ', 'ｽﾞ', 'ｾﾞ', 'ｿﾞ', 'ﾀﾞ', 'ﾁﾞ', 'ﾂﾞ', 'ﾃﾞ', 'ﾄﾞ', 'ﾊﾞ', 'ﾋﾞ', 'ﾌﾞ', 'ﾍﾞ', 'ﾎﾞ', 'ﾊﾟ', 'ﾋﾟ', 'ﾌﾟ', 'ﾍﾟ', 'ﾎﾟ', 'ｷｬ', 'ｷｭ', 'ｷｮ', 'ｷﾞｬ', 'ｷﾞｭ', 'ｷﾞｮ', 'ｼｬ', 'ｼｭ', 'ｼｮ', 'ｼﾞｬ', 'ｼﾞｭ', 'ｼﾞｮ', 'ﾁｬ', 'ﾁｭ', 'ﾁｮ', 'ﾆｬ', 'ﾆｭ', 'ﾆｮ', 'ﾋｬ', 'ﾋｭ', 'ﾋｮ', 'ﾐｬ', 'ﾐｭ', 'ﾐｮ', 'ﾋﾞｬ', 'ﾋﾞｭ', 'ﾋﾞｮ', 'ﾋﾟｬ', 'ﾋﾟｭ', 'ﾋﾟｮ', 'ﾘｬ', 'ﾘｭ', 'ﾘｮ', 'ｰ', 'ﾔ', 'ﾕ', 'ﾖ', 'ｬ', 'ｭ', 'ｮ', 'ｧ', 'ｨ', 'ｩ', 'ｪ', 'ｫ', 'ｯ', '｡', ' ', 'ｳﾞ', 'ｱ', 'ｲ', 'ｳ', 'ｴ', 'ｵ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9');
            var bigKana = Array('カ', 'キ', 'ク', 'ケ', 'コ', 'サ', 'シ', 'ス', 'セ', 'ソ', 'タ', 'チ', 'ツ', 'テ', 'ト', 'ナ', '二', 'ヌ', 'ネ', 'ノ', 'ハ', 'ヒ', 'フ', 'ヘ', 'ホ', 'マ', 'ミ', 'ム', 'メ', 'モ', 'ラ', 'リ', 'ル', 'レ', 'ロ', 'ワ', 'ヲ', 'ン', 'ガ', 'ギ', 'グ', 'ゲ', 'ゴ', 'ザ', 'ジ', 'ズ', 'ゼ', 'ゾ', 'ダ', 'ヂ', 'ヅ', 'デ', 'ド', 'バ', 'ビ', 'ブ', 'ベ', 'ボ', 'パ', 'ピ', 'プ', 'ペ', 'ポ', 'キャ', 'キュ', 'キョ', 'ギャ', 'ギュ', 'ギョ', 'シャ', 'シュ', 'ショ', 'ジャ', 'ジュ', 'ジョ', 'チャ', 'チュ', 'チョ', 'ニャ', 'ニュ', 'ニョ', 'ヒャ', 'ヒュ', 'ヒョ', 'ミャ', 'ミュ', 'ミョ', 'ビャ', 'ビュ', 'ビョ', 'ピャ', 'ピュ', 'ピョ', 'リャ', 'リュ', 'リョ', 'ー', 'ヤ', 'ユ', 'ヨ', 'ャ', 'ュ', 'ョ', 'ァ', 'ィ', 'ゥ', 'ェ', 'ォ', 'ッ', '。', '　', 'ヴ', 'ア', 'イ', 'ウ', 'エ', 'オ', '０', '１', '２', '３', '４', '５', '６', '７', '８', '９');
            var ckanaVal = '';
            for (var i = 0; i < kanaVal.length; i++) {
                //var index = smallKana.indexOf(kanaVal.charAt(i)); //indexOf and stri[i] don't work on ie
                console.log(kanaVal);
                var index = jQuery.inArray(kanaVal.charAt(i), bigKana);
                console.log(index);
                if (index !== -1) {
                    ckanaVal += smallKana[index];
                } else {
                    ckanaVal += kanaVal.charAt(i);
                }
            }

            return ckanaVal;
        };

しかし、番号には交換できていません。

**Comment by k1LoW** [comment]
> いいえ。下記にソースを追加すると、対応できると思います

あ、このリポジトリのjquery-autokanaで半角カナに対応しないという意味です。

機能追加したい場合、リポジトリをforkしていただいてご自身で対応していただくのが良いかと思います。

こちらのリポジトリもarchiveしておきます。
コメントありがとうございました。
